// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Dart bindings for TieCode C API.
class TiecApi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TiecApi(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TiecApi.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int tc_create_context(ffi.Pointer<ffi.Char> options_json) {
    return _tc_create_context(options_json);
  }

  late final _tc_create_contextPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Char>)>>(
        'tc_create_context',
      );
  late final _tc_create_context = _tc_create_contextPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int tc_create_compiler(int context_handle) {
    return _tc_create_compiler(context_handle);
  }

  late final _tc_create_compilerPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.IntPtr)>>(
        'tc_create_compiler',
      );
  late final _tc_create_compiler = _tc_create_compilerPtr
      .asFunction<int Function(int)>();

  int tc_compiler_set_diagnostic_handler(
    int compiler_handle,
    tc_report_diagnostic diagnostic_reporter,
  ) {
    return _tc_compiler_set_diagnostic_handler(
      compiler_handle,
      diagnostic_reporter,
    );
  }

  late final _tc_compiler_set_diagnostic_handlerPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.IntPtr, tc_report_diagnostic)>
      >('tc_compiler_set_diagnostic_handler');
  late final _tc_compiler_set_diagnostic_handler =
      _tc_compiler_set_diagnostic_handlerPtr
          .asFunction<int Function(int, tc_report_diagnostic)>();

  int tc_compiler_compile_files(
    int compiler_handle,
    int file_count,
    ffi.Pointer<ffi.Pointer<ffi.Char>> files,
  ) {
    return _tc_compiler_compile_files(compiler_handle, file_count, files);
  }

  late final _tc_compiler_compile_filesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('tc_compiler_compile_files');
  late final _tc_compiler_compile_files = _tc_compiler_compile_filesPtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int tc_create_ide_service(int context_handle) {
    return _tc_create_ide_service(context_handle);
  }

  late final _tc_create_ide_servicePtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.IntPtr)>>(
        'tc_create_ide_service',
      );
  late final _tc_create_ide_service = _tc_create_ide_servicePtr
      .asFunction<int Function(int)>();

  int tc_ide_service_compile(
    int ide_service_handle,
    int file_count,
    ffi.Pointer<ffi.Pointer<ffi.Char>> files,
  ) {
    return _tc_ide_service_compile(ide_service_handle, file_count, files);
  }

  late final _tc_ide_service_compilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('tc_ide_service_compile');
  late final _tc_ide_service_compile = _tc_ide_service_compilePtr
      .asFunction<int Function(int, int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int tc_ide_service_edit_source(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Char> initial_text,
  ) {
    return _tc_ide_service_edit_source(ide_service_handle, uri, initial_text);
  }

  late final _tc_ide_service_edit_sourcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tc_ide_service_edit_source');
  late final _tc_ide_service_edit_source = _tc_ide_service_edit_sourcePtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  int tc_ide_service_edit_source_incremental(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Char> change_json,
  ) {
    return _tc_ide_service_edit_source_incremental(
      ide_service_handle,
      uri,
      change_json,
    );
  }

  late final _tc_ide_service_edit_source_incrementalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tc_ide_service_edit_source_incremental');
  late final _tc_ide_service_edit_source_incremental =
      _tc_ide_service_edit_source_incrementalPtr
          .asFunction<
            int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
          >();

  int tc_ide_service_create_source(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Char> initial_text,
  ) {
    return _tc_ide_service_create_source(ide_service_handle, uri, initial_text);
  }

  late final _tc_ide_service_create_sourcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tc_ide_service_create_source');
  late final _tc_ide_service_create_source = _tc_ide_service_create_sourcePtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  int tc_ide_service_delete_source(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
  ) {
    return _tc_ide_service_delete_source(ide_service_handle, uri);
  }

  late final _tc_ide_service_delete_sourcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_delete_source');
  late final _tc_ide_service_delete_source = _tc_ide_service_delete_sourcePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  int tc_ide_service_rename_source(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Char> new_uri,
  ) {
    return _tc_ide_service_rename_source(ide_service_handle, uri, new_uri);
  }

  late final _tc_ide_service_rename_sourcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.IntPtr,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tc_ide_service_rename_source');
  late final _tc_ide_service_rename_source = _tc_ide_service_rename_sourcePtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  ffi.Pointer<ffi.Char> tc_ide_service_complete(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
  ) {
    return _tc_ide_service_complete(ide_service_handle, params_json);
  }

  late final _tc_ide_service_completePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_complete');
  late final _tc_ide_service_complete = _tc_ide_service_completePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tc_ide_service_hover(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
  ) {
    return _tc_ide_service_hover(ide_service_handle, params_json);
  }

  late final _tc_ide_service_hoverPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_hover');
  late final _tc_ide_service_hover = _tc_ide_service_hoverPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tc_ide_service_lint_file(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
  ) {
    return _tc_ide_service_lint_file(ide_service_handle, uri);
  }

  late final _tc_ide_service_lint_filePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_lint_file');
  late final _tc_ide_service_lint_file = _tc_ide_service_lint_filePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tc_ide_service_lint_all(int ide_service_handle) {
    return _tc_ide_service_lint_all(ide_service_handle);
  }

  late final _tc_ide_service_lint_allPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.IntPtr)>>(
        'tc_ide_service_lint_all',
      );
  late final _tc_ide_service_lint_all = _tc_ide_service_lint_allPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> tc_ide_service_highlight(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> uri,
  ) {
    return _tc_ide_service_highlight(ide_service_handle, uri);
  }

  late final _tc_ide_service_highlightPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_highlight');
  late final _tc_ide_service_highlight = _tc_ide_service_highlightPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tc_ide_service_find_definition(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
  ) {
    return _tc_ide_service_find_definition(ide_service_handle, params_json);
  }

  late final _tc_ide_service_find_definitionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_find_definition');
  late final _tc_ide_service_find_definition =
      _tc_ide_service_find_definitionPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> tc_ide_service_find_references(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
  ) {
    return _tc_ide_service_find_references(ide_service_handle, params_json);
  }

  late final _tc_ide_service_find_referencesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_find_references');
  late final _tc_ide_service_find_references =
      _tc_ide_service_find_referencesPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
          >();

  ffi.Pointer<ffi.Char> tc_ide_service_prepare_rename(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
  ) {
    return _tc_ide_service_prepare_rename(ide_service_handle, params_json);
  }

  late final _tc_ide_service_prepare_renamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.IntPtr, ffi.Pointer<ffi.Char>)
        >
      >('tc_ide_service_prepare_rename');
  late final _tc_ide_service_prepare_rename = _tc_ide_service_prepare_renamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> tc_ide_service_rename(
    int ide_service_handle,
    ffi.Pointer<ffi.Char> params_json,
    ffi.Pointer<ffi.Char> new_name,
  ) {
    return _tc_ide_service_rename(ide_service_handle, params_json, new_name);
  }

  late final _tc_ide_service_renamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.IntPtr,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('tc_ide_service_rename');
  late final _tc_ide_service_rename = _tc_ide_service_renamePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();
}

abstract class tc_error {
  static const int TC_OK = 0;
  static const int TC_HANDLE_INVALID = 1;
}

typedef tc_report_diagnostic =
    ffi.Pointer<ffi.NativeFunction<tc_report_diagnosticFunction>>;
typedef tc_report_diagnosticFunction =
    ffi.Void Function(ffi.Pointer<ffi.Char> diagnostic_json);
typedef Darttc_report_diagnosticFunction =
    void Function(ffi.Pointer<ffi.Char> diagnostic_json);

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 0;
